{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_24_2025/backtests_package/T07_SequentialHarmony_PKG.py\", line 96, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_24_2025/backtests_package/T07_SequentialHarmony_PKG.py\", line 83, in next\n    equity = self._broker.getvalue()\nAttributeError: '_Broker' object has no attribute 'getvalue'\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_24_2025/backtests_package/T07_SequentialHarmony_PKG.py` failed. (See above for error)\n",
  "execution_time": 2.131477,
  "timestamp": "2025-10-24T12:12:49.370578"
}