{
  "success": false,
  "return_code": 1,
  "stdout": "\ud83c\udf19 Moon Dev: Initializing PulsarFlow Strategy \u2728\n\n",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_25_2025/backtests/T00_PulsarFlow_DEBUG_v8.py\", line 224, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_25_2025/backtests/T00_PulsarFlow_DEBUG_v8.py\", line 98, in next\n    close = self.data.Close.iloc[current_i]\nAttributeError: '_Array' object has no attribute 'iloc'\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_25_2025/backtests/T00_PulsarFlow_DEBUG_v8.py` failed. (See above for error)\n",
  "execution_time": 0.976272,
  "timestamp": "2025-10-25T06:16:54.565023"
}