{
  "success": false,
  "return_code": 1,
  "stdout": "",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_25_2025/backtests_optimized/T07_VigorConvergence_OPT_v6.py\", line 122, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_25_2025/backtests_optimized/T07_VigorConvergence_OPT_v6.py\", line 117, in next\n    if self._i % 100 == 0:\nAttributeError: 'VigorConvergence' object has no attribute '_i'\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_25_2025/backtests_optimized/T07_VigorConvergence_OPT_v6.py` failed. (See above for error)\n",
  "execution_time": 1.168072,
  "timestamp": "2025-10-25T06:19:27.470797"
}